### ISSUE TITLE
Example/Usage Code

### ISSUE THREAD

**Issue by andrewwagner** [glesperance/node-kissmetrics#1]
Hello,

I was wondering if you had available any snippets of usage/example code for this package.  I'm hoping to integrate KissMetrics into a node.js app, with some events needing to be tracked outside of the browser.  Any help is greatly appreciated.

Thanks

**Comment by antonisaantoniou** [comment]
Hello, 

It there any way to call identify in this module?

**Comment by glesperance** [comment]
@antonisa90 no ; each call to the library is meant to be accompanied by the identifying information of the user to which we're attaching the event.
